
service: lambdaalb

provider:
  name: aws
  region: us-west-2
  runtime: dotnetcore3.1

custom:
  vpcConfig:
    vpcId: vpc-c93faeb1
    subnets:
      - subnet-8740bdda
      - subnet-9301e3eb
      - subnet-bd6c1896
      - subnet-ef1718a4

package:
  individually: true
      
functions:
  webapi:
    handler: CsharpHandlers::Namespace.API::FunctionHandler
    package:
      artifact: bin/Release/netcoreapp3.1/lambdaalb.zip
    events:
      - alb:
          listenerArn: 
            Ref: Listener
          priority: 1
          conditions:
            path: /api/*

resources:
  Resources:
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt
          - WebapiLambdaFunction
          - Arn
        Action: 'lambda:InvokeFunction'
        Principal: elasticloadbalancing.amazonaws.com

    SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties: 
        GroupDescription: Generic HTTP Security Group
        SecurityGroupIngress: 
          -
            CidrIp: 0.0.0.0/0
            FromPort: 80
            IpProtocol: tcp
            ToPort: 80
        VpcId: ${self:custom.vpcConfig.vpcId}

    LoadBalancer:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties: 
        SecurityGroups: 
          - Ref: SecurityGroup
        Subnets: 
          ${self:custom.vpcConfig.subnets}

    TargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties: 
        TargetType: lambda
        Targets:
          - Id: !GetAtt [ WebapiLambdaFunction, Arn ]

    Listener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties: 
        DefaultActions: 
          - 
            TargetGroupArn:
              Ref: TargetGroup
            Type: forward
        LoadBalancerArn:
          Ref: LoadBalancer
        Port: 80
        Protocol: HTTP

  Outputs:
    LoadBalancerDNSName:
      Value: !GetAtt LoadBalancer.DNSName
  
